apiVersion: argocd.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: argocd-provider
spec:
  serverAddr: argocd-instance-server.argocd.svc:443 # e.g. cluster IP 100.104.204.154
  insecure: true
  plainText: false
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-argocd
      name: argocd-credentials
      key: authToken