apiVersion: projects.argocd.crossplane.io/v1alpha1
kind: Project
metadata:
  name: {{ .Values.project.name }}
  annotations:
    "helm.sh/hook": "pre-install,post-delete"
    "helm.sh/hook-weight": "1"  # Runs after namespace is created and before it is deleted
spec:
  forProvider:
    description: {{ .Values.project.desc }}
    destinations:
      - namespace: {{ .Values.project.namespace }}
        server: '*'
    sourceRepos:
      - '*'
  providerConfigRef:
    name: argocd-provider