apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: argo-cd-instance
  namespace: crossplane-argocd
spec:
  forProvider:
    manifest:
      apiVersion: helm.crossplane.io/v1alpha1
      kind: Release
      metadata:
        name: argocd-instance
        namespace: argocd
      spec:
          forProvider:
            chart:
              name: argo-cd
              repository: https://argoproj.github.io/argo-helm
              version: "7.5.2"
            namespace: argocd
          providerConfigRef:
            name: helm-provider
  providerConfigRef:
    name: kubernetes-provider
